bs: 2
n_gpus: 1
num_workers: 4
metric_to_save: mIoU
model_dtype: FLOAT32
scheduler:
  total_iter: 500
  type: WarmupOneCycleLR
  constructor_kwargs:
    warmup_iters: 50
    warmup_ratio: 1.0e-06
    final_div_factor: .inf
    pct_start: 0
    anneal_strategy: cos
    use_beta1: false
    update_momentum: false
optimizer:
  lr: 0.001
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.001
  gradient_clip: 'inf'
datasets:
  root: C:/data/DinoCrack
  train: ADE20K:split=TRAIN
  val: ADE20K:split=VAL
train:
  diceloss_weight: 0.0
  celoss_weight: 1.0
decoder_head:
  type: linear
  backbone_out_layers: LAST
  use_cls_token: false
  use_batchnorm: true
  use_backbone_norm: true
  num_classes: 2
transforms:
  train:
    img_size: 512
    random_img_size_ratio_range:
    - 0.5
    - 2.0
    crop_size:
    - 512
    - 512
    flip_prob: 0.5
  eval:
    img_size: 512
eval:
  compute_metric_per_image: false
  reduce_zero_label: true
  mode: slide
  crop_size: 512
  stride: 341
  eval_interval: 100
  use_tta: false
output_dir: debug_output
seed: 42
